### ISSUE TITLE
What’s the name of the font in the screenshot?

### ISSUE THREAD

**Issue by michalrus** [osener/wring#1]
Hey, could you tell me and @kmicu what’s the name of the beautiful font you used in https://github.com/osener/wring/blob/f9317975c6b03fcc20a4e0ef2db01ddb2468674a/resources/media/img1.png?

![here](https://raw.githubusercontent.com/osener/wring/f9317975c6b03fcc20a4e0ef2db01ddb2468674a/resources/media/img1.png)

Thank you for that and for this project! :smile_cat:

**Comment by ozanvos** [comment]
The font is [M+ 1mn](https://mplus-fonts.osdn.jp/about-en.html), more specifically my modified version of it with decreased line height: [mplus-1mn.zip](https://github.com/osener/wring/files/162085/mplus-1mn.zip).

Glad you liked it!

**Comment by michalrus** [comment]
Thank you very much! :smiley_cat: :sweat_smile: 

Best!
