### ISSUE TITLE
Extract javascript values

### ISSUE THREAD

**Issue by Salamafet** [osener/wring#2]
Hi,
I want to extract values from JavaScript in a HTML page.

I have many lines like this:

```
<script language="JavaScript" type="text/javascript">
//<![CDATA[
write_value("112",490);
//]]>
</script>
```

In this example I want to extract 490.

How I can do that ?

Thanks

**Comment by ozanvos** [comment]
This is not the best fit for this utility, but you can do something like `wring text <file or url> script | grep -Po '(?<=\",)[0-9]+'`.

**Comment by Salamafet** [comment]
Thanks a lot :)

You did a great job

**Comment by ozanvos** [comment]
You're welcome!
